server:
  port: 8080

spring:
  #  resources:
  #    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://localhost:3306/e_mall?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化连接数量
      initial-size: 5
      # 最小线连接数量
      min-idle: 5
      # 最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为tru
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      # 配置监拉统计挡成的filters. stat: 监控统计、Log4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,log4j2
      # 配置后台监控
      stat-view-servlet:
        # 允许访问的地址，这里因为时本地所以配置当前机器
        allow: 127.0.0.1
        # 是否开启访问
        enabled: true
        # 是否能够重置数据
        reset-enable: false
        # 管理页面登陆的用户名
        login-username: admin
        # 管理页面登陆的密码
        login-password: admin
  web:
    resources:
      static-locations: file:${file-path}, classpath:static

  redis:
    host: localhost
    port: 6379
    # password:

# 静态资源路径
file-path: d:/files/e_mall/imgs/

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: cn.tedu.mall.service.pojo.po
  configuration:
    # 将下划线映射为驼峰格式
    map-underscore-to-camel-case: true
  type-handlers-package: cn.tedu.mall.common.handler.PrefixTypeHandler

logging:
  level:
    cn.tedu: debug

#配置支付宝沙箱测试
alipay:
  # appId
  appId: 9021000136675072
  # 应用私钥
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCEPbPFclJ6DtyOc8iMWjcLfu3WKcpvy8tAQyIJrh8V3lDcnglgbE6hh2WhueRrmbp7ngQh7J4Ccj8UiBwbG5/ZcCs8Zf5sgZOvf0hy4kkWKm2w6vmU4licThDcbjM0ukVfZEij7HcE6ISxG3YB9Z3DWpJECdrSNWJoFcCQw6+oi8gPokMg55uOXlodrDqZ/CMbIC0AOzls7NpauT2LVpNWntTvLD4FVk6vA8qKIqAZv+TGqfKyOZmmOb/eyzjz0SPXigdopnEUdRD0cMGaWKUcfhkBZ/nxljHrfviRGoIuxGOXFiWCP3XYo5LBfstl6yForZ3ZbzELrl4q/Ce8w03ZAgMBAAECggEAar+AKaeiSmNKyTdPsXR1sLLyfInZnytMVACdLmE/OKDwd1afTRXA14V7lfSAHhfHQFiLD3N5DZJ5tzI0NfGztItma2gN3DsxI17E9fASfXEcgM79T6DzVKFz3OycKzkeHOXP+Xs9jFnCG1GGjgheJL8tCP1HhZ6QZGMCwhkk6BFVmRqiv1ZEdLIZkgb+augAwp7Npe33pHAj9RUU5ASAy6eyNA/J9fmS+aEie/a9X45TzTBfmzY+9JH9XVdrhogREuPxeiRKxDAu6Zc95MR5VrADK0psHPxb2IMRBhMohRGZgWfz8YWp80NOVZH1wZLKQe2mnUQ1n7vEnv8rMSwkAQKBgQDmFi5SpI91K6IUZQKnxP+Vc5cRrZsqY1pgBIFdmcNXQEIaLDBhqplfnCxMJWNmxM7/vl49+P2eRaS4HSW4JSKhawOunheNDcqLTtfEQ4W7Rb7rtu3WlCfYlsUGrwCnunjAgaYVb5UNjTM04YWDOGQPWIiyAutkv7eG4+ihC0zbWQKBgQCTInP23RxTacYICtElJpIf/6gdMSGXpYGxtD2fqof9W6jpS4quI0tkCYQy3YEWx5MXxuelKcgSTPv5+SWEEbCdyfd3qLrB0kOq7FHLlEcpSt9bdXMmCzfd8NbWEVRFsjNme/6HBOj/h5s7n+6yhx10UjyBDh3G6ARFvB1LlmQ2gQKBgQCwkIzztnywOc+jPvCOtko78fwYANV17dBIpqxvm7OfnRwc4ZQvHq+cA0irFnX1Q0pmTzwa6pwVfPQupY9whG7S2EB3G7KO9+pahSJm5joVwCwGztYtOHxrZSfFPT6PeDV55QQCpyIGyDhneDjwvbFrZVFg6YSiR80aooK+MuHD4QKBgGAMV6NJiBozrGDHnuwfl7hnzjjwP7udAWMeBDRcwFV2JnfVJnyy8Z4mUDRcQM68DZux7rn04nR/6OWv7PugCKmYlIF6lh+8wQutJWA+NY4RIGm17Ctjm164v6YSve6Ze9BlFSzS2b8lqQJtTwcgCOxMWs7shie4gkF7oawcSuMBAoGBAKzT67uULUZoPA9A+yzeP1ucRKeBuD/p02Hfu8f50VLq9jmR5W14f3G5PXY21gN1Zb8de0l/bPMTgifaeiD76kvYa02npJqfhm8sucXOkZPHZQWtN/jIYlFoOkywg41G92fmZL71t1BU5YV7eHWIDBIboA5NMfQ+/HzD2z37ZR4I
  # 支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgNdQ1/4Lvu49SuluOHIL5ow9AiVSz63YI3ZpAOCQaBxIErMX+Qu5F/RV4MwaEHq/kPGLNjqwUTmYpm2JUKL9cID1r7YVU+gKMRellZ4D3C6bJHWLMr55xnaxhlAd3M9MRcYCbPt3O0XhMOAXnJwUPveWhmNHEopCO4uflZ/65PHyxX+wx4xNPvYcD/r6H/frDunMY/tKnSJMsovjBErC4skmrlSbirTBc4USj03e4qtix88wgRY/gEzktwi5m0BroHmYYUmASUgRbZPRk0PcY0agYN7OhPn7Pj9mEAI+rjS4DCk3FpdCVHZWA+XyL+V0fTT+XdubJx647vb3XugR3wIDAQAB
  # 外网, 如本地项目启动测试, 需配置内网穿透, 本项目使用natapp代理的url+/alipay/notify
  notifyUrl: http://963c4s.natappfree.cc/alipay/notify
