server:
  port: 8080

## 告诉mybatis mapper的地址
#mybatis:
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/e_mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  web:
    resources:
      static-locations: file:${file-path}, classpath:static

file-path:
  d:/files

logging:
  level:
    cn.tedu: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true

